### ISSUE TITLE
TclError: couldn't read file "azure-dark.tcl": no such file or directory

### ISSUE THREAD

**Issue by Jerryno** [rdbende/Azure-ttk-theme#12]
The downloaded example.py throws this error:
```
root.tk.call('source', 'azure-dark.tcl')
_tkinter.TclError: couldn't read file "azure-dark.tcl": no such file or directory
```

![azure](https://user-images.githubusercontent.com/10379975/122049538-d4b70800-cde2-11eb-89cf-a3389c2a636b.png)

Win 10, Python 3.9.0

**Comment by rdbende** [comment]
> no such file or directory

Looks like you give an incorrect path, check the path to azure-dark.tcl and fix it!

**Comment by Jerryno** [comment]
Yeah the working directory is different. This is what fixed it for me:
```
dir_path = os.path.dirname(os.path.realpath(__file__))
root.tk.call('source', os.path.join(dir_path, 'azure-dark.tcl'))
```
