### ISSUE TITLE
Treeview item icon barely visible when selected

### ISSUE THREAD

**Issue by danbodoh** [rdbende/Azure-ttk-theme#13]
The Treeview "right" and "down" on an item are barely visible when the item is selected.

Full disclosure - I switched the Tcl/TK require to 8.5 since I don't have 8.6 installed

**Comment by rdbende** [comment]
Ok, thanks, I've put it to my TODO list. If I think so, it only started with version `1.4` when I changed the highlight color to blue. I can even remove `8.6` because from version `1.4.1` the theme uses gifs instead of png, which was supported by `8.5`.

**Comment by rdbende** [comment]
Fixed by  f31c18c
