### ISSUE TITLE
Link error in README

### ISSUE THREAD

**Issue by UnsignedArduino** [rdbende/Azure-ttk-theme#14]
At the very top the link to (I'm assuming) your forest theme you typed `github.dom` instead of `github.com`

![image](https://user-images.githubusercontent.com/38868705/124324092-66977280-db50-11eb-9b26-5aff99dcd456.png)

**Comment by rdbende** [comment]
Oh the two are so close. Thanks.

**Comment by rdbende** [comment]
Fixed: a0398e2
