### ISSUE TITLE
Using theme with Tabs - Performance issue

### ISSUE THREAD

**Issue by kobi-adler** [rdbende/Azure-ttk-theme#2]
After I added tabs to my app with the theme activated I started to experience performance issues.

Also, the tabs and menu bar don't have any visual effect from the theme.

But I really like your Dark theme so keep going :)

**Comment by rdbende** [comment]
First of all thank you for trying my theme!
Can you send a screenshot?
The tabs should work, but unfortunately the theme can only change the appearance of ttk widgets, not the simple tkinter widgets, so only the foreground and background colors of the menubar can be changed.

![image](https://user-images.githubusercontent.com/77941087/107927568-76366600-6f77-11eb-96dc-d607a9bbd2ff.png)
