### ISSUE TITLE
Exception has occurred: TclError couldn't read file "./theme/light.tcl": no such file or directory

### ISSUE THREAD

**Issue by zSynctic** [rdbende/Azure-ttk-theme#21]

**Comment by rdbende** [comment]
This issue has been fixed in September, I just forgot to make a new release for it. It should work with version 2.1.

**Comment by zSynctic** [comment]
How can I get version 2.1

**Comment by rdbende** [comment]
You can download the archive here: https://github.com/rdbende/Azure-ttk-theme/releases/tag/v2.1.0

**Comment by zSynctic** [comment]
Ok thanks I will try that

**Comment by rdbende** [comment]
You probably have specified a wrong path to the `azure.tcl` file.

**Comment by zSynctic** [comment]
It's the first time for me to use a theme so I don't know how to really use one I just downloaded the zip and extracted it into the folder where I'm doing tkinter, so you mean I add a path from system environment variables to the azure.tcl file?

**Comment by rdbende** [comment]
If you have the `azure.tcl` in the same directory, then it should work. Except if the editor you're using changes the working directory when running the file. Then you could check out this comment: https://github.com/rdbende/Azure-ttk-theme/issues/12#issuecomment-862441699

**Comment by zSynctic** [comment]
![image](https://user-images.githubusercontent.com/71632495/148814017-17069916-77a3-4c9c-9e27-a87cc5db9c6e.png)

**Comment by rdbende** [comment]
The best solution is to write `Azure-ttk-theme-2.1.0/azure.tcl` in the code, but it's also a solution to put `idk.py` into `Azure-ttk-theme-2.1.0` folder.

**Comment by zSynctic** [comment]
I added idk.py into azure-ttk-theme-2.1.0 folder but still it doesn't works

**Comment by zSynctic** [comment]
![image](https://user-images.githubusercontent.com/71632495/148816784-326e5271-f53a-489e-8bb8-ba0ce1343a84.png)

**Comment by rdbende** [comment]
Then you should try what #12 did.

**Comment by zSynctic** [comment]
![image](https://user-images.githubusercontent.com/71632495/148817123-7d00f9da-af1f-4539-91d6-5f879283791d.png)

**Comment by rdbende** [comment]
Instead of `style.theme_use('azure')` you should use `root.tk.call('set_theme', 'light')` to set the theme.

**Comment by zSynctic** [comment]
You mean like this? 
![image](https://user-images.githubusercontent.com/71632495/148818021-d4031eb6-6dc8-4d2a-88b2-d39c9f369f35.png)

**Comment by rdbende** [comment]
Yes, but please check out the readme, where it is written that some styles changed names, and now you have to use `Accent.TButton` instead of `Accentbutton`.

**Comment by zSynctic** [comment]
Oh ok thank you
