### ISSUE TITLE
Error in example.py: it still uses old names "Accentbutton" and "Togglebutton"

### ISSUE THREAD

**Issue by OscarL** [rdbende/Azure-ttk-theme#4]
Just as the title says, currently you can read:

In line 100:

    accentbutton = ttk.Button(root, text='Accent button', style='Accentbutton', command=callback)

and on line 103:

    toggle = ttk.Checkbutton(root, text='Toggle button', style='Togglebutton', variable=f, offvalue=0, onvalue=1)

Other than that... the theme looks great! Thanks for your work!

**Comment by rdbende** [comment]
Ohh thanks! I fixed it!
