### ISSUE TITLE
Images arent transparent

### ISSUE THREAD

**Issue by git123userhub** [rdbende/Azure-ttk-theme#42]
So the images arent transparent, but why is that?
The images not being transparent causes an issue, and that the widget doesnt blend in with the background.
Now obviously, this is an easy peasy fix, but what is the reason for the images not being transparent?

**Comment by rdbende** [comment]
Initially the images' background were transparent, but it made the theme **incredibly** laggy on Window$. And Tkinter will put a background behind any (transparent or not) image anyway, so I rather removed the transparency.

TLDR: It wouldn't blend in with the background even if the images' background were transparent.
