### ISSUE TITLE
TCL files have an error

### ISSUE THREAD

**Issue by git123userhub** [rdbende/Azure-ttk-theme#51]
When i tried to use the azure theme for my project, tkinter gave me an error saying:
**_tkinter.TclError: can't read "I(box-disabled)": no such element in array**

**Comment by git123userhub** [comment]
I think i figured it out, for some reason, there is no image for 'box disabled', so the code using 'box-disabled' is trying to reference something that doesnt exist, which is why tkinter prints out an error.

**Comment by AdomasGrigolis** [comment]
I have just got this issue as well. Is it a new patch or smth?

**Comment by git123userhub** [comment]
there must be something wrong with the newer versions, i have an old version thats working, i can share the google drive link for you

**Comment by AdomasGrigolis** [comment]
Would be nice, thank you. Also do you know if I can still use ttkthemes in parallel with this? I have sort of theme selection panel.

**Comment by git123userhub** [comment]
Dont really know, but I think you could integrate the theme into the package if you know some TCL and some handling with packages.

**Comment by rdbende** [comment]
Fixed with 965b527
