### ISSUE TITLE
Does not install properly using pip

### ISSUE THREAD

**Issue by kevin-partin** [rdbende/Azure-ttk-theme#62]
Under Debian 12
``
$ sudo python3 -m pip install --break-system-packages azure-ttk
Collecting azure-ttk
  Downloading azure_ttk-0.0.0.tar.gz (829 bytes)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: azure-ttk
  Building wheel for azure-ttk (setup.py) ... done
  Created wheel for azure-ttk: filename=azure_ttk-0.0.0-py3-none-any.whl size=1049 sha256=5b2c5b8b1932c6fb27ee1d058e84d19451c13f761f8fab18bf3835d460cb5e81
  Stored in directory: /root/.cache/pip/wheels/bc/89/bb/ad82345b74ab7e02621b00b8d7969ec8c27e9411ece5613b7a
Successfully built azure-ttk
Installing collected packages: azure-ttk
Successfully installed azure-ttk-0.0.0
$ python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> import tkinter as tk
\>>> root = tk.Tk()
\>>> root.tk.call('source', 'azure.tcl')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_tkinter.TclError: couldn't read file "azure.tcl": no such file or directory
\>>> import azure_ttk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'azure_ttk'

`

**Comment by rdbende** [comment]
FYI: This theme is not yet published to Pypi. The `azure-ttk` package exists only to reserve the name.
