### ISSUE TITLE
Cropped treeview items and troubles with launch

### ISSUE THREAD

**Issue by ghost** [rdbende/Azure-ttk-theme#64]
First of all, I would like to note that this theme looks really amazing. I like it. When I tried to launch an example, I stumbled upon two issues. First of all, script does not launch when invoked with Windows Python Launcher for some reason (but from terminal and IDLE it works fine, so I have no idea why). Something slightly similar happened to me previously. It may have something to do with a filesystem. Second, program looks blurry, just as any tkinter on my computer. I resolved that by standard method in this situation:
```python
from ctypes import windll
windll.shcore.SetProcessDpiAwareness(1)
```
It resolves that problem, but unfortunately, introduces another: all items from treeview are cropped.  Screenshot attached.
<img width="467" alt="Screenshot 2024-01-23 230104" src="https://github.com/rdbende/Azure-ttk-theme/assets/129331730/4bcbe014-9bae-43c2-abc2-38235b7c7dd0">

**Comment by oehhar** [comment]
Here is an eventually unrelated comment from the unerlying TCL/Tk community.
The overlapping Treeview row is an artefact of Tk 8.6 when larger Fonts are used.
At least, Tk 9.0 (currently beta) solves this (and a lot of other) scaling issues.

RDBene probably knowa this. A common solution may be found on the wiki page:
[ttk::treeview](https://wiki.tcl-lang.org/page/ttk%3A%3Atreeview)
See "Big font overlap".

Sorry when unrelated,
Harald

**Comment by ghost** [comment]
Okay, it may have nothing to do with that particular theme then. Also, issue with Python Laucher fixed. It was indeed a filesystem problem. Unrelated to that theme also:
```python
import os
path = os.path.dirname(__file__) + '\\azure.tcl'
root.tk.call('source', path)
# instead of
# root.tk.call('source', 'azure.tcl')
```

**Comment by ghost** [comment]
Issue fixed. It was indeed a tkinter problem:
```python
style = ttk.Style()
style.configure('Treeview', rowheight=40)
```
Thanks for hint, @oehhar.

**Comment by oehhar** [comment]
Great !
