### ISSUE TITLE
LGPL Licensing question

### ISSUE THREAD

**Issue by bodand** [rdbende/Azure-ttk-theme#7]
Hello there!

Firstly, good job on the theme; looks really good 😄 

The problem is that I don't know how to interpret the licensing requirements of the LGPL on a programing
language (Tcl) that doesn't understand the concept of linking - for other Tcl scripts at least.

The LGPL says this:

```
  5. A program that contains no derivative of any portion of the
Library, but is designed to work with the Library by being compiled or
linked with it, is called a "work that uses the Library".  Such a
work, in isolation, is not a derivative work of the Library, and
therefore falls outside the scope of this License.

  However, linking a "work that uses the Library" with the Library
creates an executable that is a derivative of the Library (because it
contains portions of the Library), rather than a "work that uses the
library".  The executable is therefore covered by this License.
Section 6 states terms for distribution of such executables.
```

However, a Tcl script (the Ttk theme) is only a runtime requirement of the Tk GUI to run and does not participate in the (non-existent) compiling or linking step. Furthermore, the Library is not compiled or linked in any shape or form and is only (re)distributed only in source form. Thinking about it this way, only section 1 of the LGPL applies at all times:

```
  1. You may copy and distribute verbatim copies of the Library's
complete source code as you receive it, in any medium, provided that
you conspicuously and appropriately publish on each copy an
appropriate copyright notice and disclaimer of warranty; keep intact
all the notices that refer to this License and to the absence of any
warranty; and distribute a copy of this License along with the
Library.
[...]
```

My question is whether my conclusion aligns with the copyright owner's interpretation of the license, and if not, how is it intended to be understood.

If a more concrete example of my use-case is needed, I have a BSD 3-Clause licensed project that uses Tcl/Tk for the GUI parts, in which I'd like to use this theme; the question is whether I can do that and just distribute the theme's files (license included, of course) with the project without having to relicense it as GPL. (In which case I'm just going to go scavenge for some other theme.)

Thanks in advance,
bodand

edit:
I just realized GitHub's new beta discussions are more appropriate for this, but oh well. It's too late now. Hope it's not much of a bother.

**Comment by rdbende** [comment]
First of all, thank you for trying out the theme.

Yes, you can use the theme in this use-case, because that's how I interpret the license.

I’ve never thought of this before, that someone would want to use it out of their own use, but I’ve always liked having the software as free as possible, and I wasn’t very afraid of my copyright. If I would upload this now I would license it under MIT or BSD-3 clause, but now I am thinking about re-licensing.
