### ISSUE TITLE
How to change the entry text cursor color in dark mode

### ISSUE THREAD

**Issue by virtualdvid** [rdbende/Azure-ttk-theme#9]
Hi,

Excellent theme! Quick Question: I have been trying to change the color of the text cursor color but I'm not able to do it.

I already tried thing like `foreground="white"` or `insertbackground="white"` also I was checking the `tcl` files but I haven't be able to figure it out.

Any clue can help! Thanks!

**Comment by andreasfloros** [comment]
Add `-insertcolor $colors(-fg) \` in the Settings (below line 31) of the `azure-dark.tcl` file.

**Comment by virtualdvid** [comment]
@andreasfloros  Gracias very much! It is working perfectly!

**Comment by rdbende** [comment]
Oh sorry for the late response and thanks to @andreasfloros. It's definitely something I thought about, I just always forgot to write it in, but now I've fixed it in c1c6eb4
